[web]
prod-web-01 ansible_host=10.20.10.11
prod-web-02 ansible_host=10.20.10.12

[database]
prod-db-01 ansible_host=10.20.10.21

[monitoring]
prod-monitor-01 ansible_host=10.20.10.31

[linux:children]
web
database
monitoring

[linux:vars]
ansible_user=automation
ansible_ssh_private_key_file=~/.ssh/enterprise_automation_lab_prod
