---
- name: Deploy Nginx web servers
  hosts: web
  become: true
  gather_facts: true
  tags:
    - web
    - nginx
    - stage_02

  roles:
    - role: nginx
      tags:
        - web
        - nginx
