---
- name: Deploy PostgreSQL database server
  hosts: database
  become: true
  gather_facts: true
  tags:
    - database
    - postgresql
    - stage_02

  roles:
    - role: postgresql
      tags:
        - database
        - postgresql
