---
- name: Deploy Prometheus Node Exporter
  hosts: linux
  become: true
  gather_facts: true
  tags:
    - monitoring
    - metrics
    - node_exporter
    - stage_02

  roles:
    - role: node_exporter
      tags:
        - monitoring
        - metrics
        - node_exporter
