---
- name: Deploy Grafana visualization server
  hosts: monitoring
  become: true
  gather_facts: true
  tags:
    - monitoring
    - grafana
    - dashboards
    - stage_02

  roles:
    - role: grafana
      tags:
        - monitoring
        - grafana
        - dashboards
